import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-bgColor mx-auto text-textColor w-full max-w-[1536px] flex flex-col justify-between px-12">
            <Navbar/>
            {children}
            <Footer/>
        </div>
      </body>
    </html>
  );
}
