import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-bgColor m-auto text-textColor min-h-[100vh] w-102 flex flex-col justify-between px-12">
            <Navbar/>
            {children}
            <Footer/>
        </div>
      </body>
    </html>
  );
}
